version: '3'

services:
  postgres:
    image: postgres:13-alpine
    container_name: uol-postgres
    environment:
      - POSTGRES_USER=uol
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=uol
    ports:
      - 5432:5432
    volumes:
      - $HOME/dataset/uol/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - database-net

  backend:
    build: ./api
    container_name: uol-api
    ports:
      - 3333:3333
    volumes:
      - ./api:/usr/app
    depends_on:
      - postgres
    networks:
      - database-net

networks:
  database-net:
    driver: bridge
